/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [14.01KB] > /home/matthieu/becpg-workspace/ocearo/ocearo-ui/public/boats/ship/assets/scene-transformed.glb [327.67KB] (-2239%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const ASSET_PREFIX = process.env.ASSET_PREFIX || './';
const modelPath = `${ASSET_PREFIX}/boats/ship/assets/scene-transformed.glb`;

export function Model(props) {
   const { nodes, materials } = useGLTF(modelPath, `${ASSET_PREFIX}/draco/`);
    
  return (
    <group {...props} dispose={null}>
    <mesh geometry={nodes.Object_10.geometry} material={materials.material_0} position={[0, -0.55, 0]} rotation={[-1.558, 0.002, 3.139]} scale={0.004} />
  </group>
  )
}
