/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [17.79KB] > /home/matthieu/becpg-workspace/ocearo/ocearo-ui/public/boats/optimist/assets/scene-transformed.glb [18.61KB] (-5%)
Author: Shunsuke A. (https://sketchfab.com/ShunsukeA.)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/optimist-sailboat-8b145c47a10c40b195e79d07f7624e68
Title: optimist sailboat
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const ASSET_PREFIX = process.env.ASSET_PREFIX || './';
const modelPath = `${ASSET_PREFIX}/boats/optimist/assets/scene-transformed.glb`;

export function Model(props) {

  const { nodes, materials } = useGLTF(modelPath, `${ASSET_PREFIX}/draco/`);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body_body_0.geometry} material={materials.body} position={[-0.054, 0.272, -0.022]} rotation={[-1.571, 0.01, 0.01]} scale={[1, 5.242, 1]} />
      <mesh geometry={nodes.boom_aluminium_0.geometry} material={materials.aluminium} position={[-0.019, 2.771, 0.964]} rotation={[0, 0.01, -0.01]} scale={[0.15, 0.15, 4.609]} />
      <mesh geometry={nodes.rubber_joint__0.geometry} material={materials.rubber_joint__0} position={[-0.008, 1.407, 3.453]} rotation={[1.571, -0.01, -0.01]} scale={[-0.037, 0.056, 0.079]} />
      <mesh geometry={nodes.sail_sail_0.geometry} material={materials.sail} position={[0.038, 8.739, 0.698]} rotation={[2.356, 1.557, 2.356]} scale={[-5.728, 4.361, 4.361]} />
    </group>
  )
}
