/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [20.96KB] > /home/matthieu/becpg-workspace/ocearo/ocearo-ui/public/boats/windsurf/assets/scene-transformed.glb [144.69KB] (-590%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const ASSET_PREFIX = process.env.ASSET_PREFIX || './';

export function Model(props) {
     const modelPath = `${ASSET_PREFIX}/boats/windsurf/assets/scene-transformed.glb`;
     
     const { nodes, materials } = useGLTF(modelPath, `${ASSET_PREFIX}/draco/`);

  return (
    <group {...props} dispose={null}>
       <mesh geometry={nodes['body_Material_#30_0'].geometry} material={materials.Material_30} position={[-0.007, 0, -0.071]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002} />
   </group>
  )
}
