/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [58.49KB] > /home/matthieu/becpg-workspace/ocearo/ocearo-ui/public/boats/default/assets/scene-transformed.glb [699.57KB] (-1096%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const ASSET_PREFIX = process.env.ASSET_PREFIX || '';
const modelPath = `${ASSET_PREFIX}/boats/default/assets/scene-transformed.glb`;

export function Model(props) {

    const { nodes, materials } = useGLTF(modelPath);
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.baba_metal_0.geometry} material={materials.metal} position={[0.24, 0.895, -5.546]} rotation={[-Math.PI / 2, 0, 1.968]} scale={0.027} />
            <mesh geometry={nodes.camadadirek_fiberglass_0.geometry} material={materials.fiberglass} position={[0, 5.267, -3.711]} rotation={[2.054, 0, Math.PI]} scale={[-0.042, 0.042, 4.707]} />
            <mesh geometry={nodes.camadanyelkeni_bez_0.geometry} material={materials.material} position={[0, 5.267, -3.711]} rotation={[2.054, 0, Math.PI]} scale={[-0.042, 0.042, 4.707]} />
            <mesh geometry={nodes.duman_ahsap_0.geometry} material={materials.ahsap} position={[-0.011, 0.854, 3.487]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={[0.045, 0.045, 0.011]} />
            <mesh geometry={nodes.dumenyuvasi_cam_0.geometry} material={materials.material_5} position={[-0.011, 0.299, 3.441]} rotation={[-Math.PI / 2, 0, 1.571]} scale={0.094} />
            <mesh geometry={nodes.govde_fiberglass2_0.geometry} material={materials.fiberglass2} position={[0, 0.32, -0.897]} rotation={[0, Math.PI / 2, 0]} scale={[5.11, 0.454, 1.212]} />
        </group>
    )
}

