/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [14.01KB] > /home/matthieu/becpg-workspace/ocearo/ocearo-ui/public/boats/ship/assets/scene-transformed.glb [327.67KB] (-2239%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/boats/ship/assets/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_10.geometry} material={materials.material_0} position={[0, -0.55, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.004} />
    </group>
  )
}

useGLTF.preload('/boats/ship/assets/scene-transformed.glb')
